# Максимальное количество пати на сервере
max-party: 7

# Максимальное количество участников в одном пати
max-player-in-party: 10

# Настройки названия пати
party-name:
  max-length: 16 # Максимальная длина названия
  min-length: 5 # Минимальная длина названия

# Время действия приглашения на вступление в пати
invite-requiest-time: 30

# Настройки ТЕГа пати
tag:
  max-length: 5 # Максимальная длина ТЕГа
  min-length: 3 # Минимальная длина ТЕГа

  # Список доступных цветов ТЭГа
  colors:
    красный: "&c"

# Настройки рангов пати
ranks:
  3: "Основатель" # Владелец, основатель
  2: "Заместитель" # Заместитель
  1: "Участник" # Обычный участник пати

# Настройка чата пати
party-chat:
  symbol: "@" # Символ, который будет использоваться для чата пати
  format: "&7(&#4dff4dПати&7) &r{rank} {player} &#4dff4d- &r{message}" # Формат сообщения в чате пати
